version: 2.1

executors:
  build-executor:
    docker:
      - image: opennms/build-env:1.0-b5
        environment:
          MAVEN_OPTS: -Xmx2g -XX:ReservedCodeCacheSize=512m -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:-UseGCOverheadLimit -XX:+UseParallelGC -XX:+UseParallelOldGC

  docs-executor:
    docker:
      - image: antora/antora:2.0.0

  netlify-cli-executor:
    docker:
      - image: opennms/netlify-cli:2.8.3-b1

  package-cloud-cli-executor:
    docker:
      - image: opennms/package-cloud-cli:0.3.05-b1

  shellcheck-executor:
    docker:
      - image: opennms/shellcheck:0.5.0-b2

commands:
  set-environment:
    description: "Initialize build with setting environment variables"
    steps:
      - run:
          name: Set environment to prepare build
          command: |
            .circleci/scripts/pre-build.sh

  restore-maven-cache:
      description: "Calculate cache key and restore cache"
      steps:
        - run: 
            name: Calculate cache key from pom files
            command: |
              find . -type f -name "pom.xml" -exec sha256sum "{}" \; >> maven-dependency-cache.key
        - restore_cache:
            keys:
              - maven-dependencies-v1-{{ checksum "maven-dependency-cache.key" }}
              - maven-dependencies-v1-

  save-maven-cache:
    description: "Save Maven dependency cache"
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-v1-{{ checksum "maven-dependency-cache.key" }}
workflows:
  build-deploy:
    jobs:
      # Run build jobs for all branches and any tag
      - pre-build:
          filters:
            tags:
              only: /.*/
      - scripts-validate:
          requires:
            - pre-build
          filters:
            tags:
              only: /.*/
      - maven-validate:
          requires:
            - scripts-validate
          filters:
            tags:
              only: /.*/
      - maven-compile:
          requires:
            - maven-validate
          filters:
            tags:
              only: /.*/

jobs:
  pre-build:
    executor: build-executor
    steps:
      - checkout
      - run:
          name: Show build information
          command: |
            .circleci/scripts/system-info.sh > system-info.txt
      - store_artifacts:
          path: system-info.txt
          destination: system-info.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  scripts-validate:
    executor: shellcheck-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Validate scripts with shellcheck
          command: |
            find .circleci -type f -name '*.sh' | wc -l
            find .circleci -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

  maven-validate:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/
      - set-environment
      - restore-maven-cache
      - run:
          name: Run clean to validate project
          command: |
            .circleci/scripts/maven-validate.sh
      - save-maven-cache

  maven-compile:
    executor: build-executor
    steps:
      - attach_workspace:
          at: ~/
      - set-environment
      - restore-maven-cache
      - run:
          name: Compile source code with Maven
          command: |
            .circleci/scripts/maven-compile.sh
      - save-maven-cache
